/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RevisaPeru.GUI;

import RevisaPeru.BusinessLogic.*;
import RevisaPeru.BusinessLogic.BLO.*;
import RevisaPeru.Entities.*;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class JInFrmMark extends javax.swing.JInternalFrame {
    //Instanciamos al la logica del Negocio
    IMarkBL markBL;
    /* Patrón Singleton*/
    private static JInFrmMark nonInstance = null;
    public static JInFrmMark getIntance()
    {
        //analizamos si el objecto no a sido creado es decir si no existe
        if(nonInstance==null)
            // si no se ah instanciado la clase entonces creamos el objeto
            nonInstance = new JInFrmMark();
        return nonInstance;
    }
    /*End Singleton*/
    /* Variables locales*/
    DefaultTableModel markTableModel;
    //Object marks[]= new Object[3];
    /**
     * Creates new form JInFrmMark
     */
    private JInFrmMark() {
        initComponents();
        //Inicializamos la instancia del BL
        markBL= new MarkBL();
        markTableModel= new DefaultTableModel();
        mostrarDatos();
    }
    
    private void mostrarDatos()
    {
        List<Mark> marks= markBL.getAllFromMark();
        markTableModel.addColumn("id");
        markTableModel.addColumn("Nombre");
        markTableModel.addColumn("Descripción");        
        for(Mark m : marks) {
            markTableModel.addRow(m.toArrayObject());
        }
        this.title =markBL.getFromMarkById(3).toString();
        jTableMarks.setModel(markTableModel);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnDetails = new javax.swing.JPanel();
        jScrollPMarks = new javax.swing.JScrollPane();
        jTableMarks = new javax.swing.JTable();
        jPnFields = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestion de Marcas");

        jPnDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Listado de Marcas"));

        jTableMarks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPMarks.setViewportView(jTableMarks);

        javax.swing.GroupLayout jPnDetailsLayout = new javax.swing.GroupLayout(jPnDetails);
        jPnDetails.setLayout(jPnDetailsLayout);
        jPnDetailsLayout.setHorizontalGroup(
            jPnDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPnDetailsLayout.setVerticalGroup(
            jPnDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnDetailsLayout.createSequentialGroup()
                .addComponent(jScrollPMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        jPnFields.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Registrar Nueva Marca"));

        javax.swing.GroupLayout jPnFieldsLayout = new javax.swing.GroupLayout(jPnFields);
        jPnFields.setLayout(jPnFieldsLayout);
        jPnFieldsLayout.setHorizontalGroup(
            jPnFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPnFieldsLayout.setVerticalGroup(
            jPnFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 131, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPnFields, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPnFields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPnDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPnDetails;
    private javax.swing.JPanel jPnFields;
    private javax.swing.JScrollPane jScrollPMarks;
    private javax.swing.JTable jTableMarks;
    // End of variables declaration//GEN-END:variables
}
